---
# tasks file for Apache
- name: Update system repositories
  dnf:
    name: '*'
    state: latest
    update_cache: yes
  tags: repo
  become: yes
  become_user: root
- name: Install EPEL repositories
  dnf:
    name: epel-release
    state: present
  become: yes
  become_user: root
  tags: repo
- name: install apache2
  dnf:
    name: httpd
    state: latest
  notify:
    - start apache server
  tags: apache installation
  become: yes
  become_user: root
- name: enable module for reverse proxy
  apache2_module:
    name: "{{ item }}"
    state: present
  loop: "{{ httpd_mod }}"
  tags: enable_module
- name: create directory for conf file
  file:
    path: "{{ item }}"
    state: directory
    owner: apache
    mode: u=rwx,g=rx,o=rx
  loop: "{{ conf_dir }}"
  become: yes
  tags: conf directory
- name:  create a conf file for the reverse proxy
  template:
    src: conf.j2
    dest: "{{ conf_dir[0] }}/reverse.conf"
    owner: apache
    mode: u=rwx,g=rx,o=rx
  notify: restart apache server
  become: yes
  tags: reverse-proxy
- name: enable conf file
  file:
    src: "{{ conf_dir[0] }}/reverse.conf"
    dest: "{{ conf_dir[1] }}/reverse.conf"
    state: link
    owner: apache
    mode: u=rwx,g=rx,o=rx
  become: yes
  tags: enable conf
- name: include conf file
  blockinfile:
    path: /etc/httpd/conf/httpd.conf
    block: |
      IncludeOptional "{{ conf_dir[1] }}/*.conf"
    insertafter: EOF
    backup: yes
  notify: restart apache server
  become: yes
  tags: modify httpd conf


    

  



  